services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: '123'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - "C:/Users/thiag/OneDrive/Área de Trabalho/workspace/Formação python - Rocketseat/Bancos de dados/mysql:/var/lib/mysql"
